# Generated by Django 5.1.3 on 2024-12-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_academicuser_groups_academicuser_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicUser',
        ),
    ]
